[tool.poetry]
name = "fflib-apex-mocks"
version = "0.1.0"
description = ""
authors = ["Edmondo Porcu <edmondo.porcu@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
cumulusci = "^3.35.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
