# This is a basic workflow to help you get started with Actions

name: UpgradeApiVersions

# Controls when the workflow will run
on: 
  workflow_dispatch:
    inputs:
      api-version:
        description: 'api version in the format XX.X e.g 58.0'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Bump Version
        run: |
          find ./ -type f -exec sed -i -e 's/apple/orange/g' {} \;
          
  commit:
    needs: update
    runs-on: ubuntu-latest
    
    steps:
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: bump api to v${{inputs.api-version}}'
          new_branch: 'devops/bump-api-versions-v${{inputs.api-version}}'
          
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
